name: doublefusion
channels:
- conda-forge
dependencies:
- matplotlib=2.2.2=py36_1
- pandas=0.23.1=py36_0
- pymc3=3.4.1=py36_0
- theano=1.0.2=py36_0
- numpy=1.13.1=py36_0
- python=3.6.2=0
- scipy=0.19.1=np113py36_0
